package net.minecraft.util.datafix;

import com.google.common.collect.ImmutableMap;
import com.google.common.util.concurrent.ThreadFactoryBuilder;
import com.mojang.datafixers.DSL;
import com.mojang.datafixers.DataFixer;
import com.mojang.datafixers.DataFixerBuilder;
import com.mojang.datafixers.Typed;
import com.mojang.datafixers.schemas.Schema;
import it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.concurrent.Executor;
import java.util.concurrent.Executors;
import java.util.function.BiFunction;
import java.util.function.Function;
import java.util.function.UnaryOperator;
import java.util.stream.Collectors;
import java.util.stream.Stream;
import net.minecraft.SharedConstants;
import net.minecraft.Util;
import net.minecraft.util.datafix.fixes.AbstractArrowPickupFix;
import net.minecraft.util.datafix.fixes.AddFlagIfNotPresentFix;
import net.minecraft.util.datafix.fixes.AddNewChoices;
import net.minecraft.util.datafix.fixes.AdvancementsFix;
import net.minecraft.util.datafix.fixes.AdvancementsRenameFix;
import net.minecraft.util.datafix.fixes.AttributesRename;
import net.minecraft.util.datafix.fixes.BedItemColorFix;
import net.minecraft.util.datafix.fixes.BiomeFix;
import net.minecraft.util.datafix.fixes.BitStorageAlignFix;
import net.minecraft.util.datafix.fixes.BlendingDataFix;
import net.minecraft.util.datafix.fixes.BlendingDataRemoveFromNetherEndFix;
import net.minecraft.util.datafix.fixes.BlockEntityBannerColorFix;
import net.minecraft.util.datafix.fixes.BlockEntityBlockStateFix;
import net.minecraft.util.datafix.fixes.BlockEntityCustomNameToComponentFix;
import net.minecraft.util.datafix.fixes.BlockEntityIdFix;
import net.minecraft.util.datafix.fixes.BlockEntityJukeboxFix;
import net.minecraft.util.datafix.fixes.BlockEntityKeepPacked;
import net.minecraft.util.datafix.fixes.BlockEntityRenameFix;
import net.minecraft.util.datafix.fixes.BlockEntityShulkerBoxColorFix;
import net.minecraft.util.datafix.fixes.BlockEntitySignDoubleSidedEditableTextFix;
import net.minecraft.util.datafix.fixes.BlockEntitySignTextStrictJsonFix;
import net.minecraft.util.datafix.fixes.BlockEntityUUIDFix;
import net.minecraft.util.datafix.fixes.BlockNameFlatteningFix;
import net.minecraft.util.datafix.fixes.BlockRenameFix;
import net.minecraft.util.datafix.fixes.BlockRenameFixWithJigsaw;
import net.minecraft.util.datafix.fixes.BlockStateStructureTemplateFix;
import net.minecraft.util.datafix.fixes.CatTypeFix;
import net.minecraft.util.datafix.fixes.CauldronRenameFix;
import net.minecraft.util.datafix.fixes.CavesAndCliffsRenames;
import net.minecraft.util.datafix.fixes.ChunkBedBlockEntityInjecterFix;
import net.minecraft.util.datafix.fixes.ChunkBiomeFix;
import net.minecraft.util.datafix.fixes.ChunkDeleteIgnoredLightDataFix;
import net.minecraft.util.datafix.fixes.ChunkDeleteLightFix;
import net.minecraft.util.datafix.fixes.ChunkHeightAndBiomeFix;
import net.minecraft.util.datafix.fixes.ChunkLightRemoveFix;
import net.minecraft.util.datafix.fixes.ChunkPalettedStorageFix;
import net.minecraft.util.datafix.fixes.ChunkProtoTickListFix;
import net.minecraft.util.datafix.fixes.ChunkRenamesFix;
import net.minecraft.util.datafix.fixes.ChunkStatusFix;
import net.minecraft.util.datafix.fixes.ChunkStatusFix2;
import net.minecraft.util.datafix.fixes.ChunkStructuresTemplateRenameFix;
import net.minecraft.util.datafix.fixes.ChunkToProtochunkFix;
import net.minecraft.util.datafix.fixes.ColorlessShulkerEntityFix;
import net.minecraft.util.datafix.fixes.CriteriaRenameFix;
import net.minecraft.util.datafix.fixes.DecoratedPotFieldRenameFix;
import net.minecraft.util.datafix.fixes.DyeItemRenameFix;
import net.minecraft.util.datafix.fixes.EffectDurationFix;
import net.minecraft.util.datafix.fixes.EntityArmorStandSilentFix;
import net.minecraft.util.datafix.fixes.EntityBlockStateFix;
import net.minecraft.util.datafix.fixes.EntityBrushableBlockFieldsRenameFix;
import net.minecraft.util.datafix.fixes.EntityCatSplitFix;
import net.minecraft.util.datafix.fixes.EntityCodSalmonFix;
import net.minecraft.util.datafix.fixes.EntityCustomNameToComponentFix;
import net.minecraft.util.datafix.fixes.EntityElderGuardianSplitFix;
import net.minecraft.util.datafix.fixes.EntityEquipmentToArmorAndHandFix;
import net.minecraft.util.datafix.fixes.EntityGoatMissingStateFix;
import net.minecraft.util.datafix.fixes.EntityHealthFix;
import net.minecraft.util.datafix.fixes.EntityHorseSaddleFix;
import net.minecraft.util.datafix.fixes.EntityHorseSplitFix;
import net.minecraft.util.datafix.fixes.EntityIdFix;
import net.minecraft.util.datafix.fixes.EntityItemFrameDirectionFix;
import net.minecraft.util.datafix.fixes.EntityMinecartIdentifiersFix;
import net.minecraft.util.datafix.fixes.EntityPaintingFieldsRenameFix;
import net.minecraft.util.datafix.fixes.EntityPaintingItemFrameDirectionFix;
import net.minecraft.util.datafix.fixes.EntityPaintingMotiveFix;
import net.minecraft.util.datafix.fixes.EntityProjectileOwnerFix;
import net.minecraft.util.datafix.fixes.EntityPufferfishRenameFix;
import net.minecraft.util.datafix.fixes.EntityRavagerRenameFix;
import net.minecraft.util.datafix.fixes.EntityRedundantChanceTagsFix;
import net.minecraft.util.datafix.fixes.EntityRidingToPassengersFix;
import net.minecraft.util.datafix.fixes.EntityShulkerColorFix;
import net.minecraft.util.datafix.fixes.EntityShulkerRotationFix;
import net.minecraft.util.datafix.fixes.EntitySkeletonSplitFix;
import net.minecraft.util.datafix.fixes.EntityStringUuidFix;
import net.minecraft.util.datafix.fixes.EntityTheRenameningFix;
import net.minecraft.util.datafix.fixes.EntityTippedArrowFix;
import net.minecraft.util.datafix.fixes.EntityUUIDFix;
import net.minecraft.util.datafix.fixes.EntityVariantFix;
import net.minecraft.util.datafix.fixes.EntityWolfColorFix;
import net.minecraft.util.datafix.fixes.EntityZombieSplitFix;
import net.minecraft.util.datafix.fixes.EntityZombieVillagerTypeFix;
import net.minecraft.util.datafix.fixes.EntityZombifiedPiglinRenameFix;
import net.minecraft.util.datafix.fixes.FeatureFlagRemoveFix;
import net.minecraft.util.datafix.fixes.FilteredBooksFix;
import net.minecraft.util.datafix.fixes.FilteredSignsFix;
import net.minecraft.util.datafix.fixes.ForcePoiRebuild;
import net.minecraft.util.datafix.fixes.FurnaceRecipeFix;
import net.minecraft.util.datafix.fixes.GoatHornIdFix;
import net.minecraft.util.datafix.fixes.GossipUUIDFix;
import net.minecraft.util.datafix.fixes.HeightmapRenamingFix;
import net.minecraft.util.datafix.fixes.IglooMetadataRemovalFix;
import net.minecraft.util.datafix.fixes.ItemBannerColorFix;
import net.minecraft.util.datafix.fixes.ItemCustomNameToComponentFix;
import net.minecraft.util.datafix.fixes.ItemIdFix;
import net.minecraft.util.datafix.fixes.ItemLoreFix;
import net.minecraft.util.datafix.fixes.ItemPotionFix;
import net.minecraft.util.datafix.fixes.ItemRemoveBlockEntityTagFix;
import net.minecraft.util.datafix.fixes.ItemRenameFix;
import net.minecraft.util.datafix.fixes.ItemShulkerBoxColorFix;
import net.minecraft.util.datafix.fixes.ItemSpawnEggFix;
import net.minecraft.util.datafix.fixes.ItemStackEnchantmentNamesFix;
import net.minecraft.util.datafix.fixes.ItemStackMapIdFix;
import net.minecraft.util.datafix.fixes.ItemStackSpawnEggFix;
import net.minecraft.util.datafix.fixes.ItemStackTheFlatteningFix;
import net.minecraft.util.datafix.fixes.ItemStackUUIDFix;
import net.minecraft.util.datafix.fixes.ItemWaterPotionFix;
import net.minecraft.util.datafix.fixes.ItemWrittenBookPagesStrictJsonFix;
import net.minecraft.util.datafix.fixes.JigsawPropertiesFix;
import net.minecraft.util.datafix.fixes.JigsawRotationFix;
import net.minecraft.util.datafix.fixes.LeavesFix;
import net.minecraft.util.datafix.fixes.LegacyDragonFightFix;
import net.minecraft.util.datafix.fixes.LevelDataGeneratorOptionsFix;
import net.minecraft.util.datafix.fixes.LevelFlatGeneratorInfoFix;
import net.minecraft.util.datafix.fixes.LevelUUIDFix;
import net.minecraft.util.datafix.fixes.MapIdFix;
import net.minecraft.util.datafix.fixes.MemoryExpiryDataFix;
import net.minecraft.util.datafix.fixes.MissingDimensionFix;
import net.minecraft.util.datafix.fixes.MobSpawnerEntityIdentifiersFix;
import net.minecraft.util.datafix.fixes.NamedEntityFix;
import net.minecraft.util.datafix.fixes.NamespacedTypeRenameFix;
import net.minecraft.util.datafix.fixes.NewVillageFix;
import net.minecraft.util.datafix.fixes.ObjectiveDisplayNameFix;
import net.minecraft.util.datafix.fixes.ObjectiveRenderTypeFix;
import net.minecraft.util.datafix.fixes.OminousBannerBlockEntityRenameFix;
import net.minecraft.util.datafix.fixes.OminousBannerRenameFix;
import net.minecraft.util.datafix.fixes.OptionsAccessibilityOnboardFix;
import net.minecraft.util.datafix.fixes.OptionsAddTextBackgroundFix;
import net.minecraft.util.datafix.fixes.OptionsAmbientOcclusionFix;
import net.minecraft.util.datafix.fixes.OptionsForceVBOFix;
import net.minecraft.util.datafix.fixes.OptionsKeyLwjgl3Fix;
import net.minecraft.util.datafix.fixes.OptionsKeyTranslationFix;
import net.minecraft.util.datafix.fixes.OptionsLowerCaseLanguageFix;
import net.minecraft.util.datafix.fixes.OptionsProgrammerArtFix;
import net.minecraft.util.datafix.fixes.OptionsRenameFieldFix;
import net.minecraft.util.datafix.fixes.OverreachingTickFix;
import net.minecraft.util.datafix.fixes.PlayerUUIDFix;
import net.minecraft.util.datafix.fixes.PoiTypeRemoveFix;
import net.minecraft.util.datafix.fixes.PoiTypeRenameFix;
import net.minecraft.util.datafix.fixes.RecipesFix;
import net.minecraft.util.datafix.fixes.RecipesRenameningFix;
import net.minecraft.util.datafix.fixes.RedstoneWireConnectionsFix;
import net.minecraft.util.datafix.fixes.References;
import net.minecraft.util.datafix.fixes.RemapChunkStatusFix;
import net.minecraft.util.datafix.fixes.RemoveGolemGossipFix;
import net.minecraft.util.datafix.fixes.RenamedCoralFansFix;
import net.minecraft.util.datafix.fixes.RenamedCoralFix;
import net.minecraft.util.datafix.fixes.ReorganizePoi;
import net.minecraft.util.datafix.fixes.SavedDataFeaturePoolElementFix;
import net.minecraft.util.datafix.fixes.SavedDataUUIDFix;
import net.minecraft.util.datafix.fixes.SpawnerDataFix;
import net.minecraft.util.datafix.fixes.StatsCounterFix;
import net.minecraft.util.datafix.fixes.StatsRenameFix;
import net.minecraft.util.datafix.fixes.StriderGravityFix;
import net.minecraft.util.datafix.fixes.StructureReferenceCountFix;
import net.minecraft.util.datafix.fixes.StructureSettingsFlattenFix;
import net.minecraft.util.datafix.fixes.StructuresBecomeConfiguredFix;
import net.minecraft.util.datafix.fixes.TeamDisplayNameFix;
import net.minecraft.util.datafix.fixes.TrappedChestBlockEntityFix;
import net.minecraft.util.datafix.fixes.VariantRenameFix;
import net.minecraft.util.datafix.fixes.VillagerDataFix;
import net.minecraft.util.datafix.fixes.VillagerFollowRangeFix;
import net.minecraft.util.datafix.fixes.VillagerRebuildLevelAndXpFix;
import net.minecraft.util.datafix.fixes.VillagerTradeFix;
import net.minecraft.util.datafix.fixes.WallPropertyFix;
import net.minecraft.util.datafix.fixes.WeaponSmithChestLootTableFix;
import net.minecraft.util.datafix.fixes.WorldGenSettingsDisallowOldCustomWorldsFix;
import net.minecraft.util.datafix.fixes.WorldGenSettingsFix;
import net.minecraft.util.datafix.fixes.WorldGenSettingsHeightAndBiomeFix;
import net.minecraft.util.datafix.fixes.WriteAndReadFix;
import net.minecraft.util.datafix.fixes.ZombieVillagerRebuildXpFix;
import net.minecraft.util.datafix.schemas.NamespacedSchema;
import net.minecraft.util.datafix.schemas.V100;
import net.minecraft.util.datafix.schemas.V102;
import net.minecraft.util.datafix.schemas.V1022;
import net.minecraft.util.datafix.schemas.V106;
import net.minecraft.util.datafix.schemas.V107;
import net.minecraft.util.datafix.schemas.V1125;
import net.minecraft.util.datafix.schemas.V135;
import net.minecraft.util.datafix.schemas.V143;
import net.minecraft.util.datafix.schemas.V1451;
import net.minecraft.util.datafix.schemas.V1451_1;
import net.minecraft.util.datafix.schemas.V1451_2;
import net.minecraft.util.datafix.schemas.V1451_3;
import net.minecraft.util.datafix.schemas.V1451_4;
import net.minecraft.util.datafix.schemas.V1451_5;
import net.minecraft.util.datafix.schemas.V1451_6;
import net.minecraft.util.datafix.schemas.V1460;
import net.minecraft.util.datafix.schemas.V1466;
import net.minecraft.util.datafix.schemas.V1470;
import net.minecraft.util.datafix.schemas.V1481;
import net.minecraft.util.datafix.schemas.V1483;
import net.minecraft.util.datafix.schemas.V1486;
import net.minecraft.util.datafix.schemas.V1510;
import net.minecraft.util.datafix.schemas.V1800;
import net.minecraft.util.datafix.schemas.V1801;
import net.minecraft.util.datafix.schemas.V1904;
import net.minecraft.util.datafix.schemas.V1906;
import net.minecraft.util.datafix.schemas.V1909;
import net.minecraft.util.datafix.schemas.V1920;
import net.minecraft.util.datafix.schemas.V1928;
import net.minecraft.util.datafix.schemas.V1929;
import net.minecraft.util.datafix.schemas.V1931;
import net.minecraft.util.datafix.schemas.V2100;
import net.minecraft.util.datafix.schemas.V2501;
import net.minecraft.util.datafix.schemas.V2502;
import net.minecraft.util.datafix.schemas.V2505;
import net.minecraft.util.datafix.schemas.V2509;
import net.minecraft.util.datafix.schemas.V2519;
import net.minecraft.util.datafix.schemas.V2522;
import net.minecraft.util.datafix.schemas.V2551;
import net.minecraft.util.datafix.schemas.V2568;
import net.minecraft.util.datafix.schemas.V2571;
import net.minecraft.util.datafix.schemas.V2684;
import net.minecraft.util.datafix.schemas.V2686;
import net.minecraft.util.datafix.schemas.V2688;
import net.minecraft.util.datafix.schemas.V2704;
import net.minecraft.util.datafix.schemas.V2707;
import net.minecraft.util.datafix.schemas.V2831;
import net.minecraft.util.datafix.schemas.V2832;
import net.minecraft.util.datafix.schemas.V2842;
import net.minecraft.util.datafix.schemas.V3076;
import net.minecraft.util.datafix.schemas.V3078;
import net.minecraft.util.datafix.schemas.V3081;
import net.minecraft.util.datafix.schemas.V3082;
import net.minecraft.util.datafix.schemas.V3083;
import net.minecraft.util.datafix.schemas.V3202;
import net.minecraft.util.datafix.schemas.V3203;
import net.minecraft.util.datafix.schemas.V3204;
import net.minecraft.util.datafix.schemas.V3325;
import net.minecraft.util.datafix.schemas.V3326;
import net.minecraft.util.datafix.schemas.V3327;
import net.minecraft.util.datafix.schemas.V3328;
import net.minecraft.util.datafix.schemas.V3438;
import net.minecraft.util.datafix.schemas.V3448;
import net.minecraft.util.datafix.schemas.V501;
import net.minecraft.util.datafix.schemas.V700;
import net.minecraft.util.datafix.schemas.V701;
import net.minecraft.util.datafix.schemas.V702;
import net.minecraft.util.datafix.schemas.V703;
import net.minecraft.util.datafix.schemas.V704;
import net.minecraft.util.datafix.schemas.V705;
import net.minecraft.util.datafix.schemas.V808;
import net.minecraft.util.datafix.schemas.V99;

public class DataFixers {
   private static final BiFunction<Integer, Schema, Schema> SAME = Schema::new;
   private static final BiFunction<Integer, Schema, Schema> SAME_NAMESPACED = NamespacedSchema::new;
   private static final DataFixer dataFixer = createFixerUpper(SharedConstants.DATA_FIX_TYPES_TO_OPTIMIZE);
   public static final int BLENDING_VERSION = 3441;

   private DataFixers() {
   }

   public static DataFixer getDataFixer() {
      return dataFixer;
   }

   private static synchronized DataFixer createFixerUpper(Set<DSL.TypeReference> set) {
      DataFixerBuilder datafixerbuilder = new DataFixerBuilder(SharedConstants.getCurrentVersion().getDataVersion().getVersion());
      addFixers(datafixerbuilder);
      if (set.isEmpty()) {
         return datafixerbuilder.buildUnoptimized();
      } else {
         Executor executor = Executors.newSingleThreadExecutor((new ThreadFactoryBuilder()).setNameFormat("Datafixer Bootstrap").setDaemon(true).setPriority(1).build());
         return datafixerbuilder.buildOptimized(set, executor);
      }
   }

   private static void addFixers(DataFixerBuilder datafixerbuilder) {
      datafixerbuilder.addSchema(99, V99::new);
      Schema schema = datafixerbuilder.addSchema(100, V100::new);
      datafixerbuilder.addFixer(new EntityEquipmentToArmorAndHandFix(schema, true));
      Schema schema1 = datafixerbuilder.addSchema(101, SAME);
      datafixerbuilder.addFixer(new BlockEntitySignTextStrictJsonFix(schema1, false));
      Schema schema2 = datafixerbuilder.addSchema(102, V102::new);
      datafixerbuilder.addFixer(new ItemIdFix(schema2, true));
      datafixerbuilder.addFixer(new ItemPotionFix(schema2, false));
      Schema schema3 = datafixerbuilder.addSchema(105, SAME);
      datafixerbuilder.addFixer(new ItemSpawnEggFix(schema3, true));
      Schema schema4 = datafixerbuilder.addSchema(106, V106::new);
      datafixerbuilder.addFixer(new MobSpawnerEntityIdentifiersFix(schema4, true));
      Schema schema5 = datafixerbuilder.addSchema(107, V107::new);
      datafixerbuilder.addFixer(new EntityMinecartIdentifiersFix(schema5, true));
      Schema schema6 = datafixerbuilder.addSchema(108, SAME);
      datafixerbuilder.addFixer(new EntityStringUuidFix(schema6, true));
      Schema schema7 = datafixerbuilder.addSchema(109, SAME);
      datafixerbuilder.addFixer(new EntityHealthFix(schema7, true));
      Schema schema8 = datafixerbuilder.addSchema(110, SAME);
      datafixerbuilder.addFixer(new EntityHorseSaddleFix(schema8, true));
      Schema schema9 = datafixerbuilder.addSchema(111, SAME);
      datafixerbuilder.addFixer(new EntityPaintingItemFrameDirectionFix(schema9, true));
      Schema schema10 = datafixerbuilder.addSchema(113, SAME);
      datafixerbuilder.addFixer(new EntityRedundantChanceTagsFix(schema10, true));
      Schema schema11 = datafixerbuilder.addSchema(135, V135::new);
      datafixerbuilder.addFixer(new EntityRidingToPassengersFix(schema11, true));
      Schema schema12 = datafixerbuilder.addSchema(143, V143::new);
      datafixerbuilder.addFixer(new EntityTippedArrowFix(schema12, true));
      Schema schema13 = datafixerbuilder.addSchema(147, SAME);
      datafixerbuilder.addFixer(new EntityArmorStandSilentFix(schema13, true));
      Schema schema14 = datafixerbuilder.addSchema(165, SAME);
      datafixerbuilder.addFixer(new ItemWrittenBookPagesStrictJsonFix(schema14, true));
      Schema schema15 = datafixerbuilder.addSchema(501, V501::new);
      datafixerbuilder.addFixer(new AddNewChoices(schema15, "Add 1.10 entities fix", References.ENTITY));
      Schema schema16 = datafixerbuilder.addSchema(502, SAME);
      datafixerbuilder.addFixer(ItemRenameFix.create(schema16, "cooked_fished item renamer", (s5) -> Objects.equals(NamespacedSchema.ensureNamespaced(s5), "minecraft:cooked_fished") ? "minecraft:cooked_fish" : s5));
      datafixerbuilder.addFixer(new EntityZombieVillagerTypeFix(schema16, false));
      Schema schema17 = datafixerbuilder.addSchema(505, SAME);
      datafixerbuilder.addFixer(new OptionsForceVBOFix(schema17, false));
      Schema schema18 = datafixerbuilder.addSchema(700, V700::new);
      datafixerbuilder.addFixer(new EntityElderGuardianSplitFix(schema18, true));
      Schema schema19 = datafixerbuilder.addSchema(701, V701::new);
      datafixerbuilder.addFixer(new EntitySkeletonSplitFix(schema19, true));
      Schema schema20 = datafixerbuilder.addSchema(702, V702::new);
      datafixerbuilder.addFixer(new EntityZombieSplitFix(schema20, true));
      Schema schema21 = datafixerbuilder.addSchema(703, V703::new);
      datafixerbuilder.addFixer(new EntityHorseSplitFix(schema21, true));
      Schema schema22 = datafixerbuilder.addSchema(704, V704::new);
      datafixerbuilder.addFixer(new BlockEntityIdFix(schema22, true));
      Schema schema23 = datafixerbuilder.addSchema(705, V705::new);
      datafixerbuilder.addFixer(new EntityIdFix(schema23, true));
      Schema schema24 = datafixerbuilder.addSchema(804, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new ItemBannerColorFix(schema24, true));
      Schema schema25 = datafixerbuilder.addSchema(806, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new ItemWaterPotionFix(schema25, false));
      Schema schema26 = datafixerbuilder.addSchema(808, V808::new);
      datafixerbuilder.addFixer(new AddNewChoices(schema26, "added shulker box", References.BLOCK_ENTITY));
      Schema schema27 = datafixerbuilder.addSchema(808, 1, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new EntityShulkerColorFix(schema27, false));
      Schema schema28 = datafixerbuilder.addSchema(813, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new ItemShulkerBoxColorFix(schema28, false));
      datafixerbuilder.addFixer(new BlockEntityShulkerBoxColorFix(schema28, false));
      Schema schema29 = datafixerbuilder.addSchema(816, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new OptionsLowerCaseLanguageFix(schema29, false));
      Schema schema30 = datafixerbuilder.addSchema(820, SAME_NAMESPACED);
      datafixerbuilder.addFixer(ItemRenameFix.create(schema30, "totem item renamer", createRenamer("minecraft:totem", "minecraft:totem_of_undying")));
      Schema schema31 = datafixerbuilder.addSchema(1022, V1022::new);
      datafixerbuilder.addFixer(new WriteAndReadFix(schema31, "added shoulder entities to players", References.PLAYER));
      Schema schema32 = datafixerbuilder.addSchema(1125, V1125::new);
      datafixerbuilder.addFixer(new ChunkBedBlockEntityInjecterFix(schema32, true));
      datafixerbuilder.addFixer(new BedItemColorFix(schema32, false));
      Schema schema33 = datafixerbuilder.addSchema(1344, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new OptionsKeyLwjgl3Fix(schema33, false));
      Schema schema34 = datafixerbuilder.addSchema(1446, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new OptionsKeyTranslationFix(schema34, false));
      Schema schema35 = datafixerbuilder.addSchema(1450, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new BlockStateStructureTemplateFix(schema35, false));
      Schema schema36 = datafixerbuilder.addSchema(1451, V1451::new);
      datafixerbuilder.addFixer(new AddNewChoices(schema36, "AddTrappedChestFix", References.BLOCK_ENTITY));
      Schema schema37 = datafixerbuilder.addSchema(1451, 1, V1451_1::new);
      datafixerbuilder.addFixer(new ChunkPalettedStorageFix(schema37, true));
      Schema schema38 = datafixerbuilder.addSchema(1451, 2, V1451_2::new);
      datafixerbuilder.addFixer(new BlockEntityBlockStateFix(schema38, true));
      Schema schema39 = datafixerbuilder.addSchema(1451, 3, V1451_3::new);
      datafixerbuilder.addFixer(new EntityBlockStateFix(schema39, true));
      datafixerbuilder.addFixer(new ItemStackMapIdFix(schema39, false));
      Schema schema40 = datafixerbuilder.addSchema(1451, 4, V1451_4::new);
      datafixerbuilder.addFixer(new BlockNameFlatteningFix(schema40, true));
      datafixerbuilder.addFixer(new ItemStackTheFlatteningFix(schema40, false));
      Schema schema41 = datafixerbuilder.addSchema(1451, 5, V1451_5::new);
      datafixerbuilder.addFixer(new ItemRemoveBlockEntityTagFix(schema41, false, Set.of("minecraft:note_block", "minecraft:flower_pot", "minecraft:dandelion", "minecraft:poppy", "minecraft:blue_orchid", "minecraft:allium", "minecraft:azure_bluet", "minecraft:red_tulip", "minecraft:orange_tulip", "minecraft:white_tulip", "minecraft:pink_tulip", "minecraft:oxeye_daisy", "minecraft:cactus", "minecraft:brown_mushroom", "minecraft:red_mushroom", "minecraft:oak_sapling", "minecraft:spruce_sapling", "minecraft:birch_sapling", "minecraft:jungle_sapling", "minecraft:acacia_sapling", "minecraft:dark_oak_sapling", "minecraft:dead_bush", "minecraft:fern")));
      datafixerbuilder.addFixer(new AddNewChoices(schema41, "RemoveNoteBlockFlowerPotFix", References.BLOCK_ENTITY));
      datafixerbuilder.addFixer(new ItemStackSpawnEggFix(schema41, false, "minecraft:spawn_egg"));
      datafixerbuilder.addFixer(new EntityWolfColorFix(schema41, false));
      datafixerbuilder.addFixer(new BlockEntityBannerColorFix(schema41, false));
      datafixerbuilder.addFixer(new LevelFlatGeneratorInfoFix(schema41, false));
      Schema schema42 = datafixerbuilder.addSchema(1451, 6, V1451_6::new);
      datafixerbuilder.addFixer(new StatsCounterFix(schema42, true));
      datafixerbuilder.addFixer(new WriteAndReadFix(schema42, "Rewrite objectives", References.OBJECTIVE));
      datafixerbuilder.addFixer(new BlockEntityJukeboxFix(schema42, false));
      Schema schema43 = datafixerbuilder.addSchema(1451, 7, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new VillagerTradeFix(schema43, false));
      Schema schema44 = datafixerbuilder.addSchema(1456, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new EntityItemFrameDirectionFix(schema44, false));
      Schema schema45 = datafixerbuilder.addSchema(1458, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new EntityCustomNameToComponentFix(schema45, false));
      datafixerbuilder.addFixer(new ItemCustomNameToComponentFix(schema45, false));
      datafixerbuilder.addFixer(new BlockEntityCustomNameToComponentFix(schema45, false));
      Schema schema46 = datafixerbuilder.addSchema(1460, V1460::new);
      datafixerbuilder.addFixer(new EntityPaintingMotiveFix(schema46, false));
      Schema schema47 = datafixerbuilder.addSchema(1466, V1466::new);
      datafixerbuilder.addFixer(new ChunkToProtochunkFix(schema47, true));
      Schema schema48 = datafixerbuilder.addSchema(1470, V1470::new);
      datafixerbuilder.addFixer(new AddNewChoices(schema48, "Add 1.13 entities fix", References.ENTITY));
      Schema schema49 = datafixerbuilder.addSchema(1474, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new ColorlessShulkerEntityFix(schema49, false));
      datafixerbuilder.addFixer(BlockRenameFix.create(schema49, "Colorless shulker block fixer", (s4) -> Objects.equals(NamespacedSchema.ensureNamespaced(s4), "minecraft:purple_shulker_box") ? "minecraft:shulker_box" : s4));
      datafixerbuilder.addFixer(ItemRenameFix.create(schema49, "Colorless shulker item fixer", (s3) -> Objects.equals(NamespacedSchema.ensureNamespaced(s3), "minecraft:purple_shulker_box") ? "minecraft:shulker_box" : s3));
      Schema schema50 = datafixerbuilder.addSchema(1475, SAME_NAMESPACED);
      datafixerbuilder.addFixer(BlockRenameFix.create(schema50, "Flowing fixer", createRenamer(ImmutableMap.of("minecraft:flowing_water", "minecraft:water", "minecraft:flowing_lava", "minecraft:lava"))));
      Schema schema51 = datafixerbuilder.addSchema(1480, SAME_NAMESPACED);
      datafixerbuilder.addFixer(BlockRenameFix.create(schema51, "Rename coral blocks", createRenamer(RenamedCoralFix.RENAMED_IDS)));
      datafixerbuilder.addFixer(ItemRenameFix.create(schema51, "Rename coral items", createRenamer(RenamedCoralFix.RENAMED_IDS)));
      Schema schema52 = datafixerbuilder.addSchema(1481, V1481::new);
      datafixerbuilder.addFixer(new AddNewChoices(schema52, "Add conduit", References.BLOCK_ENTITY));
      Schema schema53 = datafixerbuilder.addSchema(1483, V1483::new);
      datafixerbuilder.addFixer(new EntityPufferfishRenameFix(schema53, true));
      datafixerbuilder.addFixer(ItemRenameFix.create(schema53, "Rename pufferfish egg item", createRenamer(EntityPufferfishRenameFix.RENAMED_IDS)));
      Schema schema54 = datafixerbuilder.addSchema(1484, SAME_NAMESPACED);
      datafixerbuilder.addFixer(ItemRenameFix.create(schema54, "Rename seagrass items", createRenamer(ImmutableMap.of("minecraft:sea_grass", "minecraft:seagrass", "minecraft:tall_sea_grass", "minecraft:tall_seagrass"))));
      datafixerbuilder.addFixer(BlockRenameFix.create(schema54, "Rename seagrass blocks", createRenamer(ImmutableMap.of("minecraft:sea_grass", "minecraft:seagrass", "minecraft:tall_sea_grass", "minecraft:tall_seagrass"))));
      datafixerbuilder.addFixer(new HeightmapRenamingFix(schema54, false));
      Schema schema55 = datafixerbuilder.addSchema(1486, V1486::new);
      datafixerbuilder.addFixer(new EntityCodSalmonFix(schema55, true));
      datafixerbuilder.addFixer(ItemRenameFix.create(schema55, "Rename cod/salmon egg items", createRenamer(EntityCodSalmonFix.RENAMED_EGG_IDS)));
      Schema schema56 = datafixerbuilder.addSchema(1487, SAME_NAMESPACED);
      datafixerbuilder.addFixer(ItemRenameFix.create(schema56, "Rename prismarine_brick(s)_* blocks", createRenamer(ImmutableMap.of("minecraft:prismarine_bricks_slab", "minecraft:prismarine_brick_slab", "minecraft:prismarine_bricks_stairs", "minecraft:prismarine_brick_stairs"))));
      datafixerbuilder.addFixer(BlockRenameFix.create(schema56, "Rename prismarine_brick(s)_* items", createRenamer(ImmutableMap.of("minecraft:prismarine_bricks_slab", "minecraft:prismarine_brick_slab", "minecraft:prismarine_bricks_stairs", "minecraft:prismarine_brick_stairs"))));
      Schema schema57 = datafixerbuilder.addSchema(1488, SAME_NAMESPACED);
      datafixerbuilder.addFixer(BlockRenameFix.create(schema57, "Rename kelp/kelptop", createRenamer(ImmutableMap.of("minecraft:kelp_top", "minecraft:kelp", "minecraft:kelp", "minecraft:kelp_plant"))));
      datafixerbuilder.addFixer(ItemRenameFix.create(schema57, "Rename kelptop", createRenamer("minecraft:kelp_top", "minecraft:kelp")));
      datafixerbuilder.addFixer(new NamedEntityFix(schema57, false, "Command block block entity custom name fix", References.BLOCK_ENTITY, "minecraft:command_block") {
         protected Typed<?> fix(Typed<?> typed) {
            return typed.update(DSL.remainderFinder(), EntityCustomNameToComponentFix::fixTagCustomName);
         }
      });
      datafixerbuilder.addFixer(new NamedEntityFix(schema57, false, "Command block minecart custom name fix", References.ENTITY, "minecraft:commandblock_minecart") {
         protected Typed<?> fix(Typed<?> typed) {
            return typed.update(DSL.remainderFinder(), EntityCustomNameToComponentFix::fixTagCustomName);
         }
      });
      datafixerbuilder.addFixer(new IglooMetadataRemovalFix(schema57, false));
      Schema schema58 = datafixerbuilder.addSchema(1490, SAME_NAMESPACED);
      datafixerbuilder.addFixer(BlockRenameFix.create(schema58, "Rename melon_block", createRenamer("minecraft:melon_block", "minecraft:melon")));
      datafixerbuilder.addFixer(ItemRenameFix.create(schema58, "Rename melon_block/melon/speckled_melon", createRenamer(ImmutableMap.of("minecraft:melon_block", "minecraft:melon", "minecraft:melon", "minecraft:melon_slice", "minecraft:speckled_melon", "minecraft:glistering_melon_slice"))));
      Schema schema59 = datafixerbuilder.addSchema(1492, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new ChunkStructuresTemplateRenameFix(schema59, false));
      Schema schema60 = datafixerbuilder.addSchema(1494, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new ItemStackEnchantmentNamesFix(schema60, false));
      Schema schema61 = datafixerbuilder.addSchema(1496, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new LeavesFix(schema61, false));
      Schema schema62 = datafixerbuilder.addSchema(1500, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new BlockEntityKeepPacked(schema62, false));
      Schema schema63 = datafixerbuilder.addSchema(1501, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new AdvancementsFix(schema63, false));
      Schema schema64 = datafixerbuilder.addSchema(1502, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new NamespacedTypeRenameFix(schema64, "Recipes fix", References.RECIPE, createRenamer(RecipesFix.RECIPES)));
      Schema schema65 = datafixerbuilder.addSchema(1506, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new LevelDataGeneratorOptionsFix(schema65, false));
      Schema schema66 = datafixerbuilder.addSchema(1510, V1510::new);
      datafixerbuilder.addFixer(BlockRenameFix.create(schema66, "Block renamening fix", createRenamer(EntityTheRenameningFix.RENAMED_BLOCKS)));
      datafixerbuilder.addFixer(ItemRenameFix.create(schema66, "Item renamening fix", createRenamer(EntityTheRenameningFix.RENAMED_ITEMS)));
      datafixerbuilder.addFixer(new NamespacedTypeRenameFix(schema66, "Recipes renamening fix", References.RECIPE, createRenamer(RecipesRenameningFix.RECIPES)));
      datafixerbuilder.addFixer(new EntityTheRenameningFix(schema66, true));
      datafixerbuilder.addFixer(new StatsRenameFix(schema66, "SwimStatsRenameFix", ImmutableMap.of("minecraft:swim_one_cm", "minecraft:walk_on_water_one_cm", "minecraft:dive_one_cm", "minecraft:walk_under_water_one_cm")));
      Schema schema67 = datafixerbuilder.addSchema(1514, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new ObjectiveDisplayNameFix(schema67, false));
      datafixerbuilder.addFixer(new TeamDisplayNameFix(schema67, false));
      datafixerbuilder.addFixer(new ObjectiveRenderTypeFix(schema67, false));
      Schema schema68 = datafixerbuilder.addSchema(1515, SAME_NAMESPACED);
      datafixerbuilder.addFixer(BlockRenameFix.create(schema68, "Rename coral fan blocks", createRenamer(RenamedCoralFansFix.RENAMED_IDS)));
      Schema schema69 = datafixerbuilder.addSchema(1624, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new TrappedChestBlockEntityFix(schema69, false));
      Schema schema70 = datafixerbuilder.addSchema(1800, V1800::new);
      datafixerbuilder.addFixer(new AddNewChoices(schema70, "Added 1.14 mobs fix", References.ENTITY));
      datafixerbuilder.addFixer(ItemRenameFix.create(schema70, "Rename dye items", createRenamer(DyeItemRenameFix.RENAMED_IDS)));
      Schema schema71 = datafixerbuilder.addSchema(1801, V1801::new);
      datafixerbuilder.addFixer(new AddNewChoices(schema71, "Added Illager Beast", References.ENTITY));
      Schema schema72 = datafixerbuilder.addSchema(1802, SAME_NAMESPACED);
      datafixerbuilder.addFixer(BlockRenameFix.create(schema72, "Rename sign blocks & stone slabs", createRenamer(ImmutableMap.of("minecraft:stone_slab", "minecraft:smooth_stone_slab", "minecraft:sign", "minecraft:oak_sign", "minecraft:wall_sign", "minecraft:oak_wall_sign"))));
      datafixerbuilder.addFixer(ItemRenameFix.create(schema72, "Rename sign item & stone slabs", createRenamer(ImmutableMap.of("minecraft:stone_slab", "minecraft:smooth_stone_slab", "minecraft:sign", "minecraft:oak_sign"))));
      Schema schema73 = datafixerbuilder.addSchema(1803, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new ItemLoreFix(schema73, false));
      Schema schema74 = datafixerbuilder.addSchema(1904, V1904::new);
      datafixerbuilder.addFixer(new AddNewChoices(schema74, "Added Cats", References.ENTITY));
      datafixerbuilder.addFixer(new EntityCatSplitFix(schema74, false));
      Schema schema75 = datafixerbuilder.addSchema(1905, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new ChunkStatusFix(schema75, false));
      Schema schema76 = datafixerbuilder.addSchema(1906, V1906::new);
      datafixerbuilder.addFixer(new AddNewChoices(schema76, "Add POI Blocks", References.BLOCK_ENTITY));
      Schema schema77 = datafixerbuilder.addSchema(1909, V1909::new);
      datafixerbuilder.addFixer(new AddNewChoices(schema77, "Add jigsaw", References.BLOCK_ENTITY));
      Schema schema78 = datafixerbuilder.addSchema(1911, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new ChunkStatusFix2(schema78, false));
      Schema schema79 = datafixerbuilder.addSchema(1914, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new WeaponSmithChestLootTableFix(schema79, false));
      Schema schema80 = datafixerbuilder.addSchema(1917, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new CatTypeFix(schema80, false));
      Schema schema81 = datafixerbuilder.addSchema(1918, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new VillagerDataFix(schema81, "minecraft:villager"));
      datafixerbuilder.addFixer(new VillagerDataFix(schema81, "minecraft:zombie_villager"));
      Schema schema82 = datafixerbuilder.addSchema(1920, V1920::new);
      datafixerbuilder.addFixer(new NewVillageFix(schema82, false));
      datafixerbuilder.addFixer(new AddNewChoices(schema82, "Add campfire", References.BLOCK_ENTITY));
      Schema schema83 = datafixerbuilder.addSchema(1925, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new MapIdFix(schema83, false));
      Schema schema84 = datafixerbuilder.addSchema(1928, V1928::new);
      datafixerbuilder.addFixer(new EntityRavagerRenameFix(schema84, true));
      datafixerbuilder.addFixer(ItemRenameFix.create(schema84, "Rename ravager egg item", createRenamer(EntityRavagerRenameFix.RENAMED_IDS)));
      Schema schema85 = datafixerbuilder.addSchema(1929, V1929::new);
      datafixerbuilder.addFixer(new AddNewChoices(schema85, "Add Wandering Trader and Trader Llama", References.ENTITY));
      Schema schema86 = datafixerbuilder.addSchema(1931, V1931::new);
      datafixerbuilder.addFixer(new AddNewChoices(schema86, "Added Fox", References.ENTITY));
      Schema schema87 = datafixerbuilder.addSchema(1936, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new OptionsAddTextBackgroundFix(schema87, false));
      Schema schema88 = datafixerbuilder.addSchema(1946, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new ReorganizePoi(schema88, false));
      Schema schema89 = datafixerbuilder.addSchema(1948, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new OminousBannerRenameFix(schema89));
      Schema schema90 = datafixerbuilder.addSchema(1953, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new OminousBannerBlockEntityRenameFix(schema90, false));
      Schema schema91 = datafixerbuilder.addSchema(1955, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new VillagerRebuildLevelAndXpFix(schema91, false));
      datafixerbuilder.addFixer(new ZombieVillagerRebuildXpFix(schema91, false));
      Schema schema92 = datafixerbuilder.addSchema(1961, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new ChunkLightRemoveFix(schema92, false));
      Schema schema93 = datafixerbuilder.addSchema(1963, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new RemoveGolemGossipFix(schema93, false));
      Schema schema94 = datafixerbuilder.addSchema(2100, V2100::new);
      datafixerbuilder.addFixer(new AddNewChoices(schema94, "Added Bee and Bee Stinger", References.ENTITY));
      datafixerbuilder.addFixer(new AddNewChoices(schema94, "Add beehive", References.BLOCK_ENTITY));
      datafixerbuilder.addFixer(new NamespacedTypeRenameFix(schema94, "Rename sugar recipe", References.RECIPE, createRenamer("minecraft:sugar", "sugar_from_sugar_cane")));
      datafixerbuilder.addFixer(new AdvancementsRenameFix(schema94, false, "Rename sugar recipe advancement", createRenamer("minecraft:recipes/misc/sugar", "minecraft:recipes/misc/sugar_from_sugar_cane")));
      Schema schema95 = datafixerbuilder.addSchema(2202, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new ChunkBiomeFix(schema95, false));
      Schema schema96 = datafixerbuilder.addSchema(2209, SAME_NAMESPACED);
      UnaryOperator<String> unaryoperator = createRenamer("minecraft:bee_hive", "minecraft:beehive");
      datafixerbuilder.addFixer(ItemRenameFix.create(schema96, "Rename bee_hive item to beehive", unaryoperator));
      datafixerbuilder.addFixer(new PoiTypeRenameFix(schema96, "Rename bee_hive poi to beehive", unaryoperator));
      datafixerbuilder.addFixer(BlockRenameFix.create(schema96, "Rename bee_hive block to beehive", unaryoperator));
      Schema schema97 = datafixerbuilder.addSchema(2211, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new StructureReferenceCountFix(schema97, false));
      Schema schema98 = datafixerbuilder.addSchema(2218, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new ForcePoiRebuild(schema98, false));
      Schema schema99 = datafixerbuilder.addSchema(2501, V2501::new);
      datafixerbuilder.addFixer(new FurnaceRecipeFix(schema99, true));
      Schema schema100 = datafixerbuilder.addSchema(2502, V2502::new);
      datafixerbuilder.addFixer(new AddNewChoices(schema100, "Added Hoglin", References.ENTITY));
      Schema schema101 = datafixerbuilder.addSchema(2503, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new WallPropertyFix(schema101, false));
      datafixerbuilder.addFixer(new AdvancementsRenameFix(schema101, false, "Composter category change", createRenamer("minecraft:recipes/misc/composter", "minecraft:recipes/decorations/composter")));
      Schema schema102 = datafixerbuilder.addSchema(2505, V2505::new);
      datafixerbuilder.addFixer(new AddNewChoices(schema102, "Added Piglin", References.ENTITY));
      datafixerbuilder.addFixer(new MemoryExpiryDataFix(schema102, "minecraft:villager"));
      Schema schema103 = datafixerbuilder.addSchema(2508, SAME_NAMESPACED);
      datafixerbuilder.addFixer(ItemRenameFix.create(schema103, "Renamed fungi items to fungus", createRenamer(ImmutableMap.of("minecraft:warped_fungi", "minecraft:warped_fungus", "minecraft:crimson_fungi", "minecraft:crimson_fungus"))));
      datafixerbuilder.addFixer(BlockRenameFix.create(schema103, "Renamed fungi blocks to fungus", createRenamer(ImmutableMap.of("minecraft:warped_fungi", "minecraft:warped_fungus", "minecraft:crimson_fungi", "minecraft:crimson_fungus"))));
      Schema schema104 = datafixerbuilder.addSchema(2509, V2509::new);
      datafixerbuilder.addFixer(new EntityZombifiedPiglinRenameFix(schema104));
      datafixerbuilder.addFixer(ItemRenameFix.create(schema104, "Rename zombie pigman egg item", createRenamer(EntityZombifiedPiglinRenameFix.RENAMED_IDS)));
      Schema schema105 = datafixerbuilder.addSchema(2511, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new EntityProjectileOwnerFix(schema105));
      Schema schema106 = datafixerbuilder.addSchema(2514, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new EntityUUIDFix(schema106));
      datafixerbuilder.addFixer(new BlockEntityUUIDFix(schema106));
      datafixerbuilder.addFixer(new PlayerUUIDFix(schema106));
      datafixerbuilder.addFixer(new LevelUUIDFix(schema106));
      datafixerbuilder.addFixer(new SavedDataUUIDFix(schema106));
      datafixerbuilder.addFixer(new ItemStackUUIDFix(schema106));
      Schema schema107 = datafixerbuilder.addSchema(2516, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new GossipUUIDFix(schema107, "minecraft:villager"));
      datafixerbuilder.addFixer(new GossipUUIDFix(schema107, "minecraft:zombie_villager"));
      Schema schema108 = datafixerbuilder.addSchema(2518, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new JigsawPropertiesFix(schema108, false));
      datafixerbuilder.addFixer(new JigsawRotationFix(schema108, false));
      Schema schema109 = datafixerbuilder.addSchema(2519, V2519::new);
      datafixerbuilder.addFixer(new AddNewChoices(schema109, "Added Strider", References.ENTITY));
      Schema schema110 = datafixerbuilder.addSchema(2522, V2522::new);
      datafixerbuilder.addFixer(new AddNewChoices(schema110, "Added Zoglin", References.ENTITY));
      Schema schema111 = datafixerbuilder.addSchema(2523, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new AttributesRename(schema111));
      Schema schema112 = datafixerbuilder.addSchema(2527, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new BitStorageAlignFix(schema112));
      Schema schema113 = datafixerbuilder.addSchema(2528, SAME_NAMESPACED);
      datafixerbuilder.addFixer(ItemRenameFix.create(schema113, "Rename soul fire torch and soul fire lantern", createRenamer(ImmutableMap.of("minecraft:soul_fire_torch", "minecraft:soul_torch", "minecraft:soul_fire_lantern", "minecraft:soul_lantern"))));
      datafixerbuilder.addFixer(BlockRenameFix.create(schema113, "Rename soul fire torch and soul fire lantern", createRenamer(ImmutableMap.of("minecraft:soul_fire_torch", "minecraft:soul_torch", "minecraft:soul_fire_wall_torch", "minecraft:soul_wall_torch", "minecraft:soul_fire_lantern", "minecraft:soul_lantern"))));
      Schema schema114 = datafixerbuilder.addSchema(2529, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new StriderGravityFix(schema114, false));
      Schema schema115 = datafixerbuilder.addSchema(2531, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new RedstoneWireConnectionsFix(schema115));
      Schema schema116 = datafixerbuilder.addSchema(2533, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new VillagerFollowRangeFix(schema116));
      Schema schema117 = datafixerbuilder.addSchema(2535, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new EntityShulkerRotationFix(schema117));
      Schema schema118 = datafixerbuilder.addSchema(2550, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new WorldGenSettingsFix(schema118));
      Schema schema119 = datafixerbuilder.addSchema(2551, V2551::new);
      datafixerbuilder.addFixer(new WriteAndReadFix(schema119, "add types to WorldGenData", References.WORLD_GEN_SETTINGS));
      Schema schema120 = datafixerbuilder.addSchema(2552, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new NamespacedTypeRenameFix(schema120, "Nether biome rename", References.BIOME, createRenamer("minecraft:nether", "minecraft:nether_wastes")));
      Schema schema121 = datafixerbuilder.addSchema(2553, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new NamespacedTypeRenameFix(schema121, "Biomes fix", References.BIOME, createRenamer(BiomeFix.BIOMES)));
      Schema schema122 = datafixerbuilder.addSchema(2558, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new MissingDimensionFix(schema122, false));
      datafixerbuilder.addFixer(new OptionsRenameFieldFix(schema122, false, "Rename swapHands setting", "key_key.swapHands", "key_key.swapOffhand"));
      Schema schema123 = datafixerbuilder.addSchema(2568, V2568::new);
      datafixerbuilder.addFixer(new AddNewChoices(schema123, "Added Piglin Brute", References.ENTITY));
      Schema schema124 = datafixerbuilder.addSchema(2571, V2571::new);
      datafixerbuilder.addFixer(new AddNewChoices(schema124, "Added Goat", References.ENTITY));
      Schema schema125 = datafixerbuilder.addSchema(2679, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new CauldronRenameFix(schema125, false));
      Schema schema126 = datafixerbuilder.addSchema(2680, SAME_NAMESPACED);
      datafixerbuilder.addFixer(ItemRenameFix.create(schema126, "Renamed grass path item to dirt path", createRenamer("minecraft:grass_path", "minecraft:dirt_path")));
      datafixerbuilder.addFixer(BlockRenameFixWithJigsaw.create(schema126, "Renamed grass path block to dirt path", createRenamer("minecraft:grass_path", "minecraft:dirt_path")));
      Schema schema127 = datafixerbuilder.addSchema(2684, V2684::new);
      datafixerbuilder.addFixer(new AddNewChoices(schema127, "Added Sculk Sensor", References.BLOCK_ENTITY));
      Schema schema128 = datafixerbuilder.addSchema(2686, V2686::new);
      datafixerbuilder.addFixer(new AddNewChoices(schema128, "Added Axolotl", References.ENTITY));
      Schema schema129 = datafixerbuilder.addSchema(2688, V2688::new);
      datafixerbuilder.addFixer(new AddNewChoices(schema129, "Added Glow Squid", References.ENTITY));
      datafixerbuilder.addFixer(new AddNewChoices(schema129, "Added Glow Item Frame", References.ENTITY));
      Schema schema130 = datafixerbuilder.addSchema(2690, SAME_NAMESPACED);
      ImmutableMap<String, String> immutablemap = ImmutableMap.<String, String>builder().put("minecraft:weathered_copper_block", "minecraft:oxidized_copper_block").put("minecraft:semi_weathered_copper_block", "minecraft:weathered_copper_block").put("minecraft:lightly_weathered_copper_block", "minecraft:exposed_copper_block").put("minecraft:weathered_cut_copper", "minecraft:oxidized_cut_copper").put("minecraft:semi_weathered_cut_copper", "minecraft:weathered_cut_copper").put("minecraft:lightly_weathered_cut_copper", "minecraft:exposed_cut_copper").put("minecraft:weathered_cut_copper_stairs", "minecraft:oxidized_cut_copper_stairs").put("minecraft:semi_weathered_cut_copper_stairs", "minecraft:weathered_cut_copper_stairs").put("minecraft:lightly_weathered_cut_copper_stairs", "minecraft:exposed_cut_copper_stairs").put("minecraft:weathered_cut_copper_slab", "minecraft:oxidized_cut_copper_slab").put("minecraft:semi_weathered_cut_copper_slab", "minecraft:weathered_cut_copper_slab").put("minecraft:lightly_weathered_cut_copper_slab", "minecraft:exposed_cut_copper_slab").put("minecraft:waxed_semi_weathered_copper", "minecraft:waxed_weathered_copper").put("minecraft:waxed_lightly_weathered_copper", "minecraft:waxed_exposed_copper").put("minecraft:waxed_semi_weathered_cut_copper", "minecraft:waxed_weathered_cut_copper").put("minecraft:waxed_lightly_weathered_cut_copper", "minecraft:waxed_exposed_cut_copper").put("minecraft:waxed_semi_weathered_cut_copper_stairs", "minecraft:waxed_weathered_cut_copper_stairs").put("minecraft:waxed_lightly_weathered_cut_copper_stairs", "minecraft:waxed_exposed_cut_copper_stairs").put("minecraft:waxed_semi_weathered_cut_copper_slab", "minecraft:waxed_weathered_cut_copper_slab").put("minecraft:waxed_lightly_weathered_cut_copper_slab", "minecraft:waxed_exposed_cut_copper_slab").build();
      datafixerbuilder.addFixer(ItemRenameFix.create(schema130, "Renamed copper block items to new oxidized terms", createRenamer(immutablemap)));
      datafixerbuilder.addFixer(BlockRenameFixWithJigsaw.create(schema130, "Renamed copper blocks to new oxidized terms", createRenamer(immutablemap)));
      Schema schema131 = datafixerbuilder.addSchema(2691, SAME_NAMESPACED);
      ImmutableMap<String, String> immutablemap1 = ImmutableMap.<String, String>builder().put("minecraft:waxed_copper", "minecraft:waxed_copper_block").put("minecraft:oxidized_copper_block", "minecraft:oxidized_copper").put("minecraft:weathered_copper_block", "minecraft:weathered_copper").put("minecraft:exposed_copper_block", "minecraft:exposed_copper").build();
      datafixerbuilder.addFixer(ItemRenameFix.create(schema131, "Rename copper item suffixes", createRenamer(immutablemap1)));
      datafixerbuilder.addFixer(BlockRenameFixWithJigsaw.create(schema131, "Rename copper blocks suffixes", createRenamer(immutablemap1)));
      Schema schema132 = datafixerbuilder.addSchema(2693, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new AddFlagIfNotPresentFix(schema132, References.WORLD_GEN_SETTINGS, "has_increased_height_already", false));
      Schema schema133 = datafixerbuilder.addSchema(2696, SAME_NAMESPACED);
      ImmutableMap<String, String> immutablemap2 = ImmutableMap.<String, String>builder().put("minecraft:grimstone", "minecraft:deepslate").put("minecraft:grimstone_slab", "minecraft:cobbled_deepslate_slab").put("minecraft:grimstone_stairs", "minecraft:cobbled_deepslate_stairs").put("minecraft:grimstone_wall", "minecraft:cobbled_deepslate_wall").put("minecraft:polished_grimstone", "minecraft:polished_deepslate").put("minecraft:polished_grimstone_slab", "minecraft:polished_deepslate_slab").put("minecraft:polished_grimstone_stairs", "minecraft:polished_deepslate_stairs").put("minecraft:polished_grimstone_wall", "minecraft:polished_deepslate_wall").put("minecraft:grimstone_tiles", "minecraft:deepslate_tiles").put("minecraft:grimstone_tile_slab", "minecraft:deepslate_tile_slab").put("minecraft:grimstone_tile_stairs", "minecraft:deepslate_tile_stairs").put("minecraft:grimstone_tile_wall", "minecraft:deepslate_tile_wall").put("minecraft:grimstone_bricks", "minecraft:deepslate_bricks").put("minecraft:grimstone_brick_slab", "minecraft:deepslate_brick_slab").put("minecraft:grimstone_brick_stairs", "minecraft:deepslate_brick_stairs").put("minecraft:grimstone_brick_wall", "minecraft:deepslate_brick_wall").put("minecraft:chiseled_grimstone", "minecraft:chiseled_deepslate").build();
      datafixerbuilder.addFixer(ItemRenameFix.create(schema133, "Renamed grimstone block items to deepslate", createRenamer(immutablemap2)));
      datafixerbuilder.addFixer(BlockRenameFixWithJigsaw.create(schema133, "Renamed grimstone blocks to deepslate", createRenamer(immutablemap2)));
      Schema schema134 = datafixerbuilder.addSchema(2700, SAME_NAMESPACED);
      datafixerbuilder.addFixer(BlockRenameFixWithJigsaw.create(schema134, "Renamed cave vines blocks", createRenamer(ImmutableMap.of("minecraft:cave_vines_head", "minecraft:cave_vines", "minecraft:cave_vines_body", "minecraft:cave_vines_plant"))));
      Schema schema135 = datafixerbuilder.addSchema(2701, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new SavedDataFeaturePoolElementFix(schema135));
      Schema schema136 = datafixerbuilder.addSchema(2702, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new AbstractArrowPickupFix(schema136));
      Schema schema137 = datafixerbuilder.addSchema(2704, V2704::new);
      datafixerbuilder.addFixer(new AddNewChoices(schema137, "Added Goat", References.ENTITY));
      Schema schema138 = datafixerbuilder.addSchema(2707, V2707::new);
      datafixerbuilder.addFixer(new AddNewChoices(schema138, "Added Marker", References.ENTITY));
      datafixerbuilder.addFixer(new AddFlagIfNotPresentFix(schema138, References.WORLD_GEN_SETTINGS, "has_increased_height_already", true));
      Schema schema139 = datafixerbuilder.addSchema(2710, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new StatsRenameFix(schema139, "Renamed play_one_minute stat to play_time", ImmutableMap.of("minecraft:play_one_minute", "minecraft:play_time")));
      Schema schema140 = datafixerbuilder.addSchema(2717, SAME_NAMESPACED);
      datafixerbuilder.addFixer(ItemRenameFix.create(schema140, "Rename azalea_leaves_flowers", createRenamer(ImmutableMap.of("minecraft:azalea_leaves_flowers", "minecraft:flowering_azalea_leaves"))));
      datafixerbuilder.addFixer(BlockRenameFix.create(schema140, "Rename azalea_leaves_flowers items", createRenamer(ImmutableMap.of("minecraft:azalea_leaves_flowers", "minecraft:flowering_azalea_leaves"))));
      Schema schema141 = datafixerbuilder.addSchema(2825, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new AddFlagIfNotPresentFix(schema141, References.WORLD_GEN_SETTINGS, "has_increased_height_already", false));
      Schema schema142 = datafixerbuilder.addSchema(2831, V2831::new);
      datafixerbuilder.addFixer(new SpawnerDataFix(schema142));
      Schema schema143 = datafixerbuilder.addSchema(2832, V2832::new);
      datafixerbuilder.addFixer(new WorldGenSettingsHeightAndBiomeFix(schema143));
      datafixerbuilder.addFixer(new ChunkHeightAndBiomeFix(schema143));
      Schema schema144 = datafixerbuilder.addSchema(2833, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new WorldGenSettingsDisallowOldCustomWorldsFix(schema144));
      Schema schema145 = datafixerbuilder.addSchema(2838, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new NamespacedTypeRenameFix(schema145, "Caves and Cliffs biome renames", References.BIOME, createRenamer(CavesAndCliffsRenames.RENAMES)));
      Schema schema146 = datafixerbuilder.addSchema(2841, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new ChunkProtoTickListFix(schema146));
      Schema schema147 = datafixerbuilder.addSchema(2842, V2842::new);
      datafixerbuilder.addFixer(new ChunkRenamesFix(schema147));
      Schema schema148 = datafixerbuilder.addSchema(2843, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new OverreachingTickFix(schema148));
      datafixerbuilder.addFixer(new NamespacedTypeRenameFix(schema148, "Remove Deep Warm Ocean", References.BIOME, createRenamer("minecraft:deep_warm_ocean", "minecraft:warm_ocean")));
      Schema schema149 = datafixerbuilder.addSchema(2846, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new AdvancementsRenameFix(schema149, false, "Rename some C&C part 2 advancements", createRenamer(ImmutableMap.of("minecraft:husbandry/play_jukebox_in_meadows", "minecraft:adventure/play_jukebox_in_meadows", "minecraft:adventure/caves_and_cliff", "minecraft:adventure/fall_from_world_height", "minecraft:adventure/ride_strider_in_overworld_lava", "minecraft:nether/ride_strider_in_overworld_lava"))));
      Schema schema150 = datafixerbuilder.addSchema(2852, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new WorldGenSettingsDisallowOldCustomWorldsFix(schema150));
      Schema schema151 = datafixerbuilder.addSchema(2967, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new StructureSettingsFlattenFix(schema151));
      Schema schema152 = datafixerbuilder.addSchema(2970, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new StructuresBecomeConfiguredFix(schema152));
      Schema schema153 = datafixerbuilder.addSchema(3076, V3076::new);
      datafixerbuilder.addFixer(new AddNewChoices(schema153, "Added Sculk Catalyst", References.BLOCK_ENTITY));
      Schema schema154 = datafixerbuilder.addSchema(3077, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new ChunkDeleteIgnoredLightDataFix(schema154));
      Schema schema155 = datafixerbuilder.addSchema(3078, V3078::new);
      datafixerbuilder.addFixer(new AddNewChoices(schema155, "Added Frog", References.ENTITY));
      datafixerbuilder.addFixer(new AddNewChoices(schema155, "Added Tadpole", References.ENTITY));
      datafixerbuilder.addFixer(new AddNewChoices(schema155, "Added Sculk Shrieker", References.BLOCK_ENTITY));
      Schema schema156 = datafixerbuilder.addSchema(3081, V3081::new);
      datafixerbuilder.addFixer(new AddNewChoices(schema156, "Added Warden", References.ENTITY));
      Schema schema157 = datafixerbuilder.addSchema(3082, V3082::new);
      datafixerbuilder.addFixer(new AddNewChoices(schema157, "Added Chest Boat", References.ENTITY));
      Schema schema158 = datafixerbuilder.addSchema(3083, V3083::new);
      datafixerbuilder.addFixer(new AddNewChoices(schema158, "Added Allay", References.ENTITY));
      Schema schema159 = datafixerbuilder.addSchema(3084, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new NamespacedTypeRenameFix(schema159, "game_event_renames_3084", References.GAME_EVENT_NAME, createRenamer(ImmutableMap.<String, String>builder().put("minecraft:block_press", "minecraft:block_activate").put("minecraft:block_switch", "minecraft:block_activate").put("minecraft:block_unpress", "minecraft:block_deactivate").put("minecraft:block_unswitch", "minecraft:block_deactivate").put("minecraft:drinking_finish", "minecraft:drink").put("minecraft:elytra_free_fall", "minecraft:elytra_glide").put("minecraft:entity_damaged", "minecraft:entity_damage").put("minecraft:entity_dying", "minecraft:entity_die").put("minecraft:entity_killed", "minecraft:entity_die").put("minecraft:mob_interact", "minecraft:entity_interact").put("minecraft:ravager_roar", "minecraft:entity_roar").put("minecraft:ring_bell", "minecraft:block_change").put("minecraft:shulker_close", "minecraft:container_close").put("minecraft:shulker_open", "minecraft:container_open").put("minecraft:wolf_shaking", "minecraft:entity_shake").build())));
      Schema schema160 = datafixerbuilder.addSchema(3086, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new EntityVariantFix(schema160, "Change cat variant type", References.ENTITY, "minecraft:cat", "CatType", Util.make(new Int2ObjectOpenHashMap(), (int2objectopenhashmap1) -> {
         int2objectopenhashmap1.defaultReturnValue("minecraft:tabby");
         int2objectopenhashmap1.put(0, "minecraft:tabby");
         int2objectopenhashmap1.put(1, "minecraft:black");
         int2objectopenhashmap1.put(2, "minecraft:red");
         int2objectopenhashmap1.put(3, "minecraft:siamese");
         int2objectopenhashmap1.put(4, "minecraft:british");
         int2objectopenhashmap1.put(5, "minecraft:calico");
         int2objectopenhashmap1.put(6, "minecraft:persian");
         int2objectopenhashmap1.put(7, "minecraft:ragdoll");
         int2objectopenhashmap1.put(8, "minecraft:white");
         int2objectopenhashmap1.put(9, "minecraft:jellie");
         int2objectopenhashmap1.put(10, "minecraft:all_black");
      })::get));
      ImmutableMap<String, String> immutablemap3 = ImmutableMap.<String, String>builder().put("textures/entity/cat/tabby.png", "minecraft:tabby").put("textures/entity/cat/black.png", "minecraft:black").put("textures/entity/cat/red.png", "minecraft:red").put("textures/entity/cat/siamese.png", "minecraft:siamese").put("textures/entity/cat/british_shorthair.png", "minecraft:british").put("textures/entity/cat/calico.png", "minecraft:calico").put("textures/entity/cat/persian.png", "minecraft:persian").put("textures/entity/cat/ragdoll.png", "minecraft:ragdoll").put("textures/entity/cat/white.png", "minecraft:white").put("textures/entity/cat/jellie.png", "minecraft:jellie").put("textures/entity/cat/all_black.png", "minecraft:all_black").build();
      datafixerbuilder.addFixer(new CriteriaRenameFix(schema160, "Migrate cat variant advancement", "minecraft:husbandry/complete_catalogue", (s2) -> immutablemap3.getOrDefault(s2, s2)));
      Schema schema161 = datafixerbuilder.addSchema(3087, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new EntityVariantFix(schema161, "Change frog variant type", References.ENTITY, "minecraft:frog", "Variant", Util.make(new Int2ObjectOpenHashMap(), (int2objectopenhashmap) -> {
         int2objectopenhashmap.put(0, "minecraft:temperate");
         int2objectopenhashmap.put(1, "minecraft:warm");
         int2objectopenhashmap.put(2, "minecraft:cold");
      })::get));
      Schema schema162 = datafixerbuilder.addSchema(3090, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new EntityPaintingFieldsRenameFix(schema162));
      Schema schema163 = datafixerbuilder.addSchema(3093, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new EntityGoatMissingStateFix(schema163));
      Schema schema164 = datafixerbuilder.addSchema(3094, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new GoatHornIdFix(schema164));
      Schema schema165 = datafixerbuilder.addSchema(3097, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new FilteredBooksFix(schema165));
      datafixerbuilder.addFixer(new FilteredSignsFix(schema165));
      Map<String, String> map = Map.of("minecraft:british", "minecraft:british_shorthair");
      datafixerbuilder.addFixer(new VariantRenameFix(schema165, "Rename british shorthair", References.ENTITY, "minecraft:cat", map));
      datafixerbuilder.addFixer(new CriteriaRenameFix(schema165, "Migrate cat variant advancement for british shorthair", "minecraft:husbandry/complete_catalogue", (s1) -> map.getOrDefault(s1, s1)));
      datafixerbuilder.addFixer(new PoiTypeRemoveFix(schema165, "Remove unpopulated villager PoI types", Set.of("minecraft:unemployed", "minecraft:nitwit")::contains));
      Schema schema166 = datafixerbuilder.addSchema(3108, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new BlendingDataRemoveFromNetherEndFix(schema166));
      Schema schema167 = datafixerbuilder.addSchema(3201, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new OptionsProgrammerArtFix(schema167));
      Schema schema168 = datafixerbuilder.addSchema(3202, V3202::new);
      datafixerbuilder.addFixer(new AddNewChoices(schema168, "Added Hanging Sign", References.BLOCK_ENTITY));
      Schema schema169 = datafixerbuilder.addSchema(3203, V3203::new);
      datafixerbuilder.addFixer(new AddNewChoices(schema169, "Added Camel", References.ENTITY));
      Schema schema170 = datafixerbuilder.addSchema(3204, V3204::new);
      datafixerbuilder.addFixer(new AddNewChoices(schema170, "Added Chiseled Bookshelf", References.BLOCK_ENTITY));
      Schema schema171 = datafixerbuilder.addSchema(3209, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new ItemStackSpawnEggFix(schema171, false, "minecraft:pig_spawn_egg"));
      Schema schema172 = datafixerbuilder.addSchema(3214, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new OptionsAmbientOcclusionFix(schema172));
      Schema schema173 = datafixerbuilder.addSchema(3319, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new OptionsAccessibilityOnboardFix(schema173));
      Schema schema174 = datafixerbuilder.addSchema(3322, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new EffectDurationFix(schema174));
      Schema schema175 = datafixerbuilder.addSchema(3325, V3325::new);
      datafixerbuilder.addFixer(new AddNewChoices(schema175, "Added displays", References.ENTITY));
      Schema schema176 = datafixerbuilder.addSchema(3326, V3326::new);
      datafixerbuilder.addFixer(new AddNewChoices(schema176, "Added Sniffer", References.ENTITY));
      Schema schema177 = datafixerbuilder.addSchema(3327, V3327::new);
      datafixerbuilder.addFixer(new AddNewChoices(schema177, "Archaeology", References.BLOCK_ENTITY));
      Schema schema178 = datafixerbuilder.addSchema(3328, V3328::new);
      datafixerbuilder.addFixer(new AddNewChoices(schema178, "Added interaction", References.ENTITY));
      Schema schema179 = datafixerbuilder.addSchema(3438, V3438::new);
      datafixerbuilder.addFixer(BlockEntityRenameFix.create(schema179, "Rename Suspicious Sand to Brushable Block", createRenamer("minecraft:suspicious_sand", "minecraft:brushable_block")));
      datafixerbuilder.addFixer(new EntityBrushableBlockFieldsRenameFix(schema179));
      datafixerbuilder.addFixer(ItemRenameFix.create(schema179, "Pottery shard renaming", createRenamer(ImmutableMap.of("minecraft:pottery_shard_archer", "minecraft:archer_pottery_shard", "minecraft:pottery_shard_prize", "minecraft:prize_pottery_shard", "minecraft:pottery_shard_arms_up", "minecraft:arms_up_pottery_shard", "minecraft:pottery_shard_skull", "minecraft:skull_pottery_shard"))));
      datafixerbuilder.addFixer(new AddNewChoices(schema179, "Added calibrated sculk sensor", References.BLOCK_ENTITY));
      Schema schema180 = datafixerbuilder.addSchema(3439, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new BlockEntitySignDoubleSidedEditableTextFix(schema180, "Updated sign text format for Signs", "minecraft:sign"));
      datafixerbuilder.addFixer(new BlockEntitySignDoubleSidedEditableTextFix(schema180, "Updated sign text format for Hanging Signs", "minecraft:hanging_sign"));
      Schema schema181 = datafixerbuilder.addSchema(3440, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new NamespacedTypeRenameFix(schema181, "Replace experimental 1.20 overworld", References.MULTI_NOISE_BIOME_SOURCE_PARAMETER_LIST, createRenamer("minecraft:overworld_update_1_20", "minecraft:overworld")));
      datafixerbuilder.addFixer(new FeatureFlagRemoveFix(schema181, "Remove 1.20 feature toggle", Set.of("minecraft:update_1_20")));
      Schema schema182 = datafixerbuilder.addSchema(3441, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new BlendingDataFix(schema182));
      Schema schema183 = datafixerbuilder.addSchema(3447, SAME_NAMESPACED);
      datafixerbuilder.addFixer(ItemRenameFix.create(schema183, "Pottery shard item renaming to Pottery sherd", createRenamer(Stream.of("minecraft:angler_pottery_shard", "minecraft:archer_pottery_shard", "minecraft:arms_up_pottery_shard", "minecraft:blade_pottery_shard", "minecraft:brewer_pottery_shard", "minecraft:burn_pottery_shard", "minecraft:danger_pottery_shard", "minecraft:explorer_pottery_shard", "minecraft:friend_pottery_shard", "minecraft:heart_pottery_shard", "minecraft:heartbreak_pottery_shard", "minecraft:howl_pottery_shard", "minecraft:miner_pottery_shard", "minecraft:mourner_pottery_shard", "minecraft:plenty_pottery_shard", "minecraft:prize_pottery_shard", "minecraft:sheaf_pottery_shard", "minecraft:shelter_pottery_shard", "minecraft:skull_pottery_shard", "minecraft:snort_pottery_shard").collect(Collectors.toMap(Function.identity(), (s) -> s.replace("_pottery_shard", "_pottery_sherd"))))));
      Schema schema184 = datafixerbuilder.addSchema(3448, V3448::new);
      datafixerbuilder.addFixer(new DecoratedPotFieldRenameFix(schema184));
      Schema schema185 = datafixerbuilder.addSchema(3450, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new RemapChunkStatusFix(schema185, "Remove liquid_carvers and heightmap chunk statuses", createRenamer(Map.of("minecraft:liquid_carvers", "minecraft:carvers", "minecraft:heightmaps", "minecraft:spawn"))));
      Schema schema186 = datafixerbuilder.addSchema(3451, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new ChunkDeleteLightFix(schema186));
      Schema schema187 = datafixerbuilder.addSchema(3459, SAME_NAMESPACED);
      datafixerbuilder.addFixer(new LegacyDragonFightFix(schema187));
   }

   private static UnaryOperator<String> createRenamer(Map<String, String> map) {
      return (s) -> map.getOrDefault(s, s);
   }

   private static UnaryOperator<String> createRenamer(String s, String s1) {
      return (s4) -> Objects.equals(s4, s) ? s1 : s4;
   }
}
